### PR TITLE
Rw/port to clojurescript

### PR DESCRIPTION
**Pull request by russellwhitaker**
@levand I've ported `immuconf` to ClojureScript/nodejs (using reader conditionals, available in Clojure v1.7+).

### CODE REVIEW

**Comment by levand** [comment]
Thanks, this is awesome.

It's going to be a little effort for me to merge (especially since I want to parse out your changes to the readme that aren't applicable to the root project), but I'll definitely do this soon.

**Comment by russellwhitaker** [comment]
@levand it's my pleasure, thanks for having provided the base library in Clojure. Let me know how/if I may assist.

**Comment by russellwhitaker** [comment]
@levand : Alex Miller told me a few minutes ago you'll be at ClojureWest as well this weekend (he's teaching the class I'm attending here at the same location, but I'm sure you know that.) Would love to meet and see if I can help with this.

**Comment by levand** [comment]
Sounds awesome! Let's definitely meet up.

It's not thing hard or complicated, just haven't done it yet :/

**Pull request closed without merging**
